### PR TITLE
Refactoring to reduce overall complexity of classes and methods

### PR DESCRIPTION
**Pull request by RyanMacG**
I took all the complex hash building and refactored it into a single hash_builder class. This includes the previous work done to add the entire user plays method.

### CODE REVIEW

**Comment by RyanMacG** [comment]
Can someone provide an update on whether or not this is likely to be accepted? If it's not I can just close this and move on.

**Comment by jemiahlee** [comment]
Sorry, with as much code change as there was, I was hoping @bhardin would look at it. :smiley:. I'll take a look this weekend and give feedback.

**Comment by jemiahlee** [comment]
So after looking through the code, there are two things that I think should be changed:

1) instance variables are unnecessary. I haven't been working in Ruby for a while, so you may be able to tell me why they are useful as instance variables instead of as lexical variables. This is an issue with the code as it is in the repo anyway, so you may have just been trying to carry-over what was already happening. The code that I wrote in this was when I was a very nascent Ruby dev, so I admit that I might not have known what i was doing. :smiley:

2) the non-functional way that the hashbuilder is being used is a style I don't love. I've put some comments in on specific lines to discuss those.

**Comment by RyanMacG** [comment]
@jemiahlee I've left some responses, if your happy with these I'll make the relevant changes

**Comment by jemiahlee** [comment]
@RyanMacG Yep, I think we're on the same page now; If you want to make the changes, we can review further then. If you'd like, I can also merge now and make the changes myself (but I assume that you, like me, prefer to make your own changes :smiley:).

**Comment by RyanMacG** [comment]
Yeah, I'll make the changes tonight or tomorrow morning and get them pushed for further review

**Comment by jemiahlee** [comment]
Ok, no worries. I'm actually getting married on Friday, so this is a busy week for me. :-) I'll try to review it before then if you get it in, but I'm going to be mostly non-responsive until about the 27th.

**Comment by RyanMacG** [comment]
@jemiahlee Congrats! That should be the relevant changes made

**Comment by jemiahlee** [comment]
Hey, can you please add me as a contributor on your fork of this repo? We had another PR come in that I think is simpler overall, but it means that someone has to deal with the rebasing of this one

**Comment by RyanMacG** [comment]
Have done, if I get time I'll try to handle the rebasing myself tomorrow

**Comment by jemiahlee** [comment]
I think I'm going to try to split this pull request into several and merge little pieces of it in smaller chunks. Based on the reorganization of the other code, I might not keep the hashbuilder part of it, but I think it will be easier to absorb that way.

**Comment by RyanMacG** [comment]
Closing in light of new request

**Pull request closed without merging**
